"""add counter comments

Revision ID: 496a10588ad8
Revises: 5ba2118af54f
Create Date: 2023-06-07 16:51:03.570141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496a10588ad8'
down_revision = '5ba2118af54f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('count_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'count_comments')
    # ### end Alembic commands ###
