"""Create new tabels with varchar_id

Revision ID: 526881b3bf4a
Revises: 7198295f6474
Create Date: 2023-06-08 00:34:34.128563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526881b3bf4a'
down_revision = '7198295f6474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('count_likes', sa.Integer(), nullable=True),
    sa.Column('count_comments', sa.Integer(), nullable=True),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('poster_link', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('id_video', sa.String(length=40), nullable=False),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id_video', sa.String(length=40), nullable=False),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_video', 'id_auther')
    )
    op.create_table('view',
    sa.Column('id_video', sa.String(length=40), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_video', 'id_user')
    )
    op.create_table('sub',
    sa.Column('id_maker', sa.Integer(), nullable=False),
    sa.Column('id_subscriber', sa.Integer(), nullable=False),
    sa.Column('datatime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_maker'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_subscriber'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_maker', 'id_subscriber')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub')
    op.drop_table('view')
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('video')
    # ### end Alembic commands ###
