"""add tabels with cascad delete

Revision ID: 5ba2118af54f
Revises: af080e621afd
Create Date: 2023-06-07 13:03:24.392999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba2118af54f'
down_revision = 'af080e621afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('count_likes', sa.Integer(), nullable=True),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('poster_link', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_video', 'id_auther')
    )
    op.create_table('view',
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_video', 'id_user')
    )
    op.create_table('sub',
    sa.Column('id_maker', sa.Integer(), nullable=False),
    sa.Column('id_subscriber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_maker'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_subscriber'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_maker', 'id_subscriber')
    )
    op.drop_table('user_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_account_pkey')
    )
    op.drop_table('sub')
    op.drop_table('view')
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('video')
    # ### end Alembic commands ###
