"""Remove attr datatime for all tables

Revision ID: 60c61582f584
Revises: 8bcfeacbf1c6
Create Date: 2023-06-06 16:14:57.829807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60c61582f584'
down_revision = '8bcfeacbf1c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'published_at')
    op.drop_column('like', 'published_at')
    op.drop_column('video', 'published_at')
    op.drop_column('view', 'published_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('like', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
