"""Add mini change tables

Revision ID: 632c574230ab
Revises: 526881b3bf4a
Create Date: 2023-06-11 19:56:50.522954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632c574230ab'
down_revision = '526881b3bf4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('link_img', sa.String(), server_default='https://storage.yandexcloud.net/urfube-emegor/default_user.png', nullable=True))
    op.add_column('video', sa.Column('count_views', sa.Integer(), server_default='0', nullable=True))
    op.add_column('video', sa.Column('nickname', sa.String(), server_default='defualt', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'nickname')
    op.drop_column('video', 'count_views')
    op.drop_column('user', 'link_img')
    # ### end Alembic commands ###
