"""add counter subs

Revision ID: 703b41e52179
Revises: 496a10588ad8
Create Date: 2023-06-07 17:18:31.379433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703b41e52179'
down_revision = '496a10588ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub', sa.Column('datatime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('count_subs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'count_subs')
    op.drop_column('sub', 'datatime')
    # ### end Alembic commands ###
