"""Add table view

Revision ID: 8bcfeacbf1c6
Revises: b85a56bbb5c7
Create Date: 2023-06-06 15:15:47.155254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcfeacbf1c6'
down_revision = 'b85a56bbb5c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view',
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id_video', 'id_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view')
    # ### end Alembic commands ###
