"""Change tables: like, comment, sub

Revision ID: 9bb7b5c88fa1
Revises: b92ac17199c9
Create Date: 2023-06-06 13:08:43.206949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb7b5c88fa1'
down_revision = 'b92ac17199c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('published_at', sa.DateTime(), nullable=False))
    op.add_column('like', sa.Column('published_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'published_at')
    op.drop_column('comment', 'published_at')
    # ### end Alembic commands ###
