"""Add attr datatime for all

Revision ID: a1fd36823d02
Revises: 02bc0007d102
Create Date: 2023-06-06 17:11:33.843158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fd36823d02'
down_revision = '02bc0007d102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('video', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('view', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view', 'published_at')
    op.drop_column('video', 'published_at')
    op.drop_column('user', 'created_at')
    op.drop_column('comment', 'published_at')
    # ### end Alembic commands ###
