"""Recreate like and cub

Revision ID: b85a56bbb5c7
Revises: 01ca4434040e
Create Date: 2023-06-06 15:09:53.971956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85a56bbb5c7'
down_revision = '01ca4434040e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('id_auther', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id_video', 'id_auther')
    )
    op.create_table('sub',
    sa.Column('id_maker', sa.Integer(), nullable=False),
    sa.Column('id_subscriber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_maker'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_subscriber'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_maker', 'id_subscriber')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub')
    op.drop_table('like')
    # ### end Alembic commands ###
