"""Change video table

Revision ID: b92ac17199c9
Revises: d5ed8d489c2c
Create Date: 2023-06-06 12:22:24.504897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92ac17199c9'
down_revision = 'd5ed8d489c2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('published_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'published_at')
    # ### end Alembic commands ###
