"""Creation other tables: comment, like, sub

Revision ID: d5ed8d489c2c
Revises: 96af8a8e14b9
Create Date: 2023-06-04 17:11:35.680659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ed8d489c2c'
down_revision = '96af8a8e14b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('id_video', sa.Integer(), nullable=False),
                    sa.Column('id_auther', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_video', sa.Integer(), nullable=False),
                    sa.Column('id_auther', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_auther'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['id_video'], ['video.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_maker', sa.Integer(), nullable=False),
                    sa.Column('id_subscriber', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_maker'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['id_subscriber'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub')
    op.drop_table('like')
    op.drop_table('comment')
    # ### end Alembic commands ###
