"""Change table: sub, like: add composite_keys

Revision ID: f585f8b16603
Revises: 9bb7b5c88fa1
Create Date: 2023-06-06 14:59:00.098222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f585f8b16603'
down_revision = '9bb7b5c88fa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'id')
    op.drop_column('sub', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('like', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
